name: Build ARM64 APK

on:
  push:
    branches:
      - master # Or your desired branch

jobs:
  build:
    runs-on: ubuntu-latest # Or a specific runner like macos-latest or windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # Specify your desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build ARM64 APK
        run: flutter build apk --release --target-platform=android-arm64 --split-per-abi

      - name: Upload ARM64 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
